version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend/temp:/app/temp
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "80:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://www.codewriter.asia
      #- VITE_API_URL=http://localhost:3001
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge